# -*- coding: utf-8 -*-
"""Boston housing prices

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fNDpiGSo1vmmC6rQmer1RrlCpVQ6LLi
"""

#import module
import tensorflow as tf
import pandas as pd
import math

#1 Data Preparation
data_path = 'https://raw.githubusercontent.com/wonup2/ML/main/boston.csv'  
boston = pd.read_csv(data_path)
print(boston.columns)  
#pd.set_option('display.max_row',None)   #show entire data
boston.head()   #top 5 data is coming

#1-1 independent, dependent data
independent = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
dependent = boston[['medv']]
#can test to make sure everything is going ok
print(independent.shape, dependent.shape)

#2 create a model
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

#3 Model training (FIT)
model.fit(independent, dependent, epochs = 1000, verbose = 0)
model.fit(independent,dependent,epochs = 10)

#4 use a model
print(model.predict(independent[5:10]))
print(dependent[5:10])