# -*- coding: utf-8 -*-
"""lemonade

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bZIEOwGFMsZOziQEQ9Ps1B8AybjvdArZ
"""

#import module
import tensorflow as tf
import pandas as pd
import math

# 1 data preparation
data_path = 'https://raw.githubusercontent.com/wonup2/ML/main/lemonade.csv'
lemonade = pd.read_csv(data_path)
lemonade.head() #top 5 data is coming, head is method in panda

#1-1 dependent
independent = lemonade[['Temperature']]
dependent = lemonade[['Sales']]
#print(independent.shape, dependent.shape)

#2 create model
X = tf.keras.layers.Input(shape=[1]) #shape = cause
Y = tf.keras.layers.Dense(1)(X) # 1 = result. in this case, one
model = tf.keras.models.Model(X,Y)
model.compile(loss = 'mse')

#3 Model training (FIT)

model.fit(independent,dependent,epochs = 2000, verbose = 0)
model.fit(independent, dependent, epochs = 10)

#4 use model
print(lemonade)
print(model.predict(independent))
print(dependent)

temperature = int(input("input tomorrow's temperature: "))
cups = float(model.predict([[temperature]]))
cups = round(cups)
print("Prepare {} cups of lemonade".format(cups))